// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ncr-submit/TossLight.tsx": () => import("../components/mockups/ncr-submit/TossLight.tsx"),
  "./components/mockups/ncr-submit/TossSimple.tsx": () => import("../components/mockups/ncr-submit/TossSimple.tsx")
};
